SELECT
c.PIDM,
c.TRM_CODE,
c.CRSE_SUBJECT_CODE,
c.CRSE_NBR,
c.CRDT_HRS,
c.CRSE_FNL_GRADE,
c.CRSE_TITLE
FROM EDW.AGG_STU_CRSE_HIST_MVW c
WHERE c.CRDT_HRS IS NOT NULL
AND c.CRSE_FNL_GRADE IS NOT NULL
AND c.CRSE_FNL_GRADE NOT IN ('T', 'GT')
AND c.CRSE_NBR NOT LIKE '%R'
AND c.PIDM IN :GTID_LIST
AND c.LVL_CODE = 'US'