SELECT DISTINCT
       SSBSECT.SSBSECT_CRN,
       SSBSECT.SSBSECT_SUBJ_CODE,
       SSBSECT.SSBSECT_CRSE_NUMB,
       SSBSECT.SSBSECT_CREDIT_HRS,
       SSBSECT.SSBSECT_SEATS_AVAIL,
       SSRMEET.SSRMEET_BEGIN_TIME,
       SSRMEET.SSRMEET_END_TIME,
       CASE WHEN LENGTH(SSRMEET.SSRMEET_SUN_DAY) > 0 THEN SSRMEET.SSRMEET_SUN_DAY ELSE 'None' END AS "Sunday",
       CASE WHEN LENGTH(SSRMEET.SSRMEET_MON_DAY) > 0 THEN SSRMEET.SSRMEET_MON_DAY ELSE 'None' END AS "Monday",
       CASE WHEN LENGTH(SSRMEET.SSRMEET_TUE_DAY) > 0 THEN SSRMEET.SSRMEET_TUE_DAY ELSE 'None' END AS "Tuesday",
       CASE WHEN LENGTH(SSRMEET.SSRMEET_WED_DAY) > 0 THEN SSRMEET.SSRMEET_WED_DAY ELSE 'None' END AS "Wednesday",
       CASE WHEN LENGTH(SSRMEET.SSRMEET_THU_DAY) > 0 THEN SSRMEET.SSRMEET_THU_DAY ELSE 'None' END AS "Thursday",
       CASE WHEN LENGTH(SSRMEET.SSRMEET_FRI_DAY) > 0 THEN SSRMEET.SSRMEET_FRI_DAY ELSE 'None' END AS "Friday",
       CASE WHEN LENGTH(SSRMEET.SSRMEET_SAT_DAY) > 0 THEN SSRMEET.SSRMEET_SAT_DAY ELSE 'None' END AS "Saturday",
       SCRRTST.SCRRTST_SEQNO,
       SCRRTST.SCRRTST_SUBJ_CODE_PREQ,
       SCRRTST.SCRRTST_CRSE_NUMB_PREQ,
       SCRRTST.SCRRTST_LEVL_CODE,
       SCRRTST.SCRRTST_MIN_GRDE,
       SCRRTST.SCRRTST_CONNECTOR,
       SCRRTST.SCRRTST_LPAREN,
       SCRRTST.SCRRTST_RPAREN
FROM (SATURN.SSBSECT SSBSECT
      INNER JOIN
      SATURN.SSRMEET SSRMEET
      ON     (SSBSECT.SSBSECT_TERM_CODE = SSRMEET.SSRMEET_TERM_CODE)
         AND (SSBSECT.SSBSECT_CRN = SSRMEET.SSRMEET_CRN))
     LEFT OUTER JOIN SATURN.SCRRTST SCRRTST
        ON     (SSBSECT.SSBSECT_SUBJ_CODE = SCRRTST.SCRRTST_SUBJ_CODE)
           AND (SSBSECT.SSBSECT_CRSE_NUMB = SCRRTST.SCRRTST_CRSE_NUMB)
WHERE (    SSBSECT.SSBSECT_TERM_CODE = '202402'
       AND SSBSECT.SSBSECT_CAMP_CODE = 'A')
ORDER BY SCRRTST.SCRRTST_SEQNO ASC